# coding: utf-8

"""
    LOCKSS Metadata Service REST API

    API of the LOCKSS Metadata REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_metadata
from lockss_metadata.models.page_info import PageInfo  # noqa: E501
from lockss_metadata.rest import ApiException


class TestPageInfo(unittest.TestCase):
    """PageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageInfo(self):
        """Test PageInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lockss_metadata.models.page_info.PageInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
