# coding: utf-8

"""
    LOCKSS Metadata Service REST API

    API of the LOCKSS Metadata REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_metadata
from lockss_metadata.models.au_metadata_page_info import AuMetadataPageInfo  # noqa: E501
from lockss_metadata.rest import ApiException


class TestAuMetadataPageInfo(unittest.TestCase):
    """AuMetadataPageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuMetadataPageInfo(self):
        """Test AuMetadataPageInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lockss_metadata.models.au_metadata_page_info.AuMetadataPageInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
