# coding: utf-8

"""
    LAAWS Metadata Service API

    API of Metadata Service for LAAWS  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_metadata
from lockss_metadata.lockss-metadata-python.item_metadata import ItemMetadata  # noqa: E501
from lockss_metadata.rest import ApiException


class TestItemMetadata(unittest.TestCase):
    """ItemMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemMetadata(self):
        """Test ItemMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lockss_metadata.models.item_metadata.ItemMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
